DROP TABLE IF EXISTS NATION;

CREATE TABLE NATION (
   N_NATIONKEY BIGINT,
   N_NAME VARCHAR(25),
   N_REGIONKEY BIGINT,
   N_COMMENT VARCHAR(152) )
WITH ( 
   FORMAT=':DATA_FORMAT', 
   CSV_DELIM='|', 
   LOCATION='kite://:KITE_LOCATION/vitessedata-public/tpch/:TPCH_SF/:DATA_FORMAT/nation/*'
);
