DROP TABLE IF EXISTS orders;

CREATE TABLE orders(
   O_ORDERKEY BIGINT,
   O_CUSTKEY BIGINT,
   O_ORDERSTATUS VARCHAR(1),
   O_TOTALPRICE DOUBLE,
   O_ORDERDATE DATE,
   O_ORDERPRIORITY VARCHAR(15),
   O_CLERK VARCHAR(15),
   O_SHIPPRIORITY INTEGER,
   O_COMMENT VARCHAR(79) )
WITH ( 
   FORMAT=':DATA_FORMAT', 
   CSV_DELIM='|', 
   LOCATION='kite://:KITE_LOCATION/vitessedata-public/tpch/:TPCH_SF/:DATA_FORMAT/orders/*'
);
