DROP TABLE IF EXISTS partsupp;

CREATE TABLE partsupp(
	PS_PARTKEY BIGINT,
   PS_SUPPKEY BIGINT,
   PS_AVAILQTY INTEGER,
   PS_SUPPLYCOST DOUBLE,
   PS_COMMENT VARCHAR(199) )
WITH ( 
   FORMAT=':DATA_FORMAT', 
   CSV_DELIM='|', 
   LOCATION='kite://:KITE_LOCATION/vitessedata-public/tpch/:TPCH_SF/:DATA_FORMAT/partsupp/*'
);
