DROP TABLE IF EXISTS part;

CREATE TABLE part(
   P_PARTKEY BIGINT,
   P_NAME VARCHAR(55),
   P_MFGR VARCHAR(25),
   P_BRAND VARCHAR(10),
   P_TYPE VARCHAR(25),
   P_SIZE INTEGER,
   P_CONTAINER VARCHAR(10),
   P_RETAILPRICE DOUBLE,
   P_COMMENT   VARCHAR(23) )
WITH ( 
   FORMAT=':DATA_FORMAT', 
   CSV_DELIM='|', 
   LOCATION='kite://:KITE_LOCATION/vitessedata-public/tpch/:TPCH_SF/:DATA_FORMAT/part/*'
);
