DROP TABLE IF EXISTS supplier;

CREATE TABLE supplier(
   S_SUPPKEY BIGINT,
   S_NAME VARCHAR(25),
   S_ADDRESS VARCHAR(40),
   S_NATIONKEY BIGINT,
   S_PHONE VARCHAR(15),
   S_ACCTBAL DOUBLE,
   S_COMMENT VARCHAR(101) )
WITH ( 
   FORMAT=':DATA_FORMAT', 
   CSV_DELIM='|', 
   LOCATION='kite://:KITE_LOCATION/vitessedata-public/tpch/:TPCH_SF/:DATA_FORMAT/supplier/*'
);
