USE kite.default;

SELECT 'NATION', COUNT(*) FROM NATION;
SELECT 'REGION', COUNT(*) FROM REGION;
SELECT 'PART', COUNT(*) FROM PART;
SELECT 'SUPPLIER', COUNT(*) FROM SUPPLIER;
SELECT 'PARTSUPP', COUNT(*) FROM PARTSUPP;
SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER;
SELECT 'ORDERS', COUNT(*) FROM ORDERS;
SELECT 'LINEITEM', COUNT(*) FROM LINEITEM;
